/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ClassificationRouteImport } from './routes/classification'
import { Route as DuplicatesRouteImport } from './routes/duplicates'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as GraphTextRouteImport } from './routes/graph-text'
import { Route as HarmonizeRouteImport } from './routes/harmonize'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MappingRouteImport } from './routes/mapping'
import { Route as MigrationRouteImport } from './routes/migration'
import { Route as NationalCodesRouteImport } from './routes/national-codes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StandardizationRouteImport } from './routes/standardization'
import { Route as MaterialsIndexRouteImport } from './routes/materials.index'
import { Route as MaterialsIdRouteImport } from './routes/materials.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificationRoute = ClassificationRouteImport.update({
  id: '/classification',
  path: '/classification',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphTextRoute = GraphTextRouteImport.update({
  id: '/graph-text',
  path: '/graph-text',
  getParentRoute: () => rootRouteImport,
} as any)
const HarmonizeRoute = HarmonizeRouteImport.update({
  id: '/harmonize',
  path: '/harmonize',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingRoute = MappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationRoute = MigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const NationalCodesRoute = NationalCodesRouteImport.update({
  id: '/national-codes',
  path: '/national-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardizationRoute = StandardizationRouteImport.update({
  id: '/standardization',
  path: '/standardization',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIndexRoute = MaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIdRoute = MaterialsIdRouteImport.update({
  id: '/materials/$id',
  path: '/materials/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/classification': typeof ClassificationRoute
  '/duplicates': typeof DuplicatesRoute
  '/governance': typeof GovernanceRoute
  '/graph': typeof GraphRoute
  '/graph-text': typeof GraphTextRoute
  '/harmonize': typeof HarmonizeRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/mapping': typeof MappingRoute
  '/migration': typeof MigrationRoute
  '/national-codes': typeof NationalCodesRoute
  '/settings': typeof SettingsRoute
  '/standardization': typeof StandardizationRoute
  '/materials/$id': typeof MaterialsIdRoute
  '/materials/': typeof MaterialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/classification': typeof ClassificationRoute
  '/duplicates': typeof DuplicatesRoute
  '/governance': typeof GovernanceRoute
  '/graph': typeof GraphRoute
  '/graph-text': typeof GraphTextRoute
  '/harmonize': typeof HarmonizeRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/mapping': typeof MappingRoute
  '/migration': typeof MigrationRoute
  '/national-codes': typeof NationalCodesRoute
  '/settings': typeof SettingsRoute
  '/standardization': typeof StandardizationRoute
  '/materials/$id': typeof MaterialsIdRoute
  '/materials': typeof MaterialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/classification': typeof ClassificationRoute
  '/duplicates': typeof DuplicatesRoute
  '/governance': typeof GovernanceRoute
  '/graph': typeof GraphRoute
  '/graph-text': typeof GraphTextRoute
  '/harmonize': typeof HarmonizeRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/mapping': typeof MappingRoute
  '/migration': typeof MigrationRoute
  '/national-codes': typeof NationalCodesRoute
  '/settings': typeof SettingsRoute
  '/standardization': typeof StandardizationRoute
  '/materials/$id': typeof MaterialsIdRoute
  '/materials/': typeof MaterialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit'
    | '/classification'
    | '/duplicates'
    | '/governance'
    | '/graph'
    | '/graph-text'
    | '/harmonize'
    | '/integrations'
    | '/login'
    | '/mapping'
    | '/migration'
    | '/national-codes'
    | '/settings'
    | '/standardization'
    | '/materials/$id'
    | '/materials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audit'
    | '/classification'
    | '/duplicates'
    | '/governance'
    | '/graph'
    | '/graph-text'
    | '/harmonize'
    | '/integrations'
    | '/login'
    | '/mapping'
    | '/migration'
    | '/national-codes'
    | '/settings'
    | '/standardization'
    | '/materials/$id'
    | '/materials'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audit'
    | '/classification'
    | '/duplicates'
    | '/governance'
    | '/graph'
    | '/graph-text'
    | '/harmonize'
    | '/integrations'
    | '/login'
    | '/mapping'
    | '/migration'
    | '/national-codes'
    | '/settings'
    | '/standardization'
    | '/materials/$id'
    | '/materials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  ClassificationRoute: typeof ClassificationRoute
  DuplicatesRoute: typeof DuplicatesRoute
  GovernanceRoute: typeof GovernanceRoute
  GraphRoute: typeof GraphRoute
  GraphTextRoute: typeof GraphTextRoute
  HarmonizeRoute: typeof HarmonizeRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  MappingRoute: typeof MappingRoute
  MigrationRoute: typeof MigrationRoute
  NationalCodesRoute: typeof NationalCodesRoute
  SettingsRoute: typeof SettingsRoute
  StandardizationRoute: typeof StandardizationRoute
  MaterialsIdRoute: typeof MaterialsIdRoute
  MaterialsIndexRoute: typeof MaterialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classification': {
      id: '/classification'
      path: '/classification'
      fullPath: '/classification'
      preLoaderRoute: typeof ClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph-text': {
      id: '/graph-text'
      path: '/graph-text'
      fullPath: '/graph-text'
      preLoaderRoute: typeof GraphTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harmonize': {
      id: '/harmonize'
      path: '/harmonize'
      fullPath: '/harmonize'
      preLoaderRoute: typeof HarmonizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping': {
      id: '/mapping'
      path: '/mapping'
      fullPath: '/mapping'
      preLoaderRoute: typeof MappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration': {
      id: '/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof MigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/national-codes': {
      id: '/national-codes'
      path: '/national-codes'
      fullPath: '/national-codes'
      preLoaderRoute: typeof NationalCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standardization': {
      id: '/standardization'
      path: '/standardization'
      fullPath: '/standardization'
      preLoaderRoute: typeof StandardizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/': {
      id: '/materials/'
      path: '/materials'
      fullPath: '/materials/'
      preLoaderRoute: typeof MaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$id': {
      id: '/materials/$id'
      path: '/materials/$id'
      fullPath: '/materials/$id'
      preLoaderRoute: typeof MaterialsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  ClassificationRoute: ClassificationRoute,
  DuplicatesRoute: DuplicatesRoute,
  GovernanceRoute: GovernanceRoute,
  GraphRoute: GraphRoute,
  GraphTextRoute: GraphTextRoute,
  HarmonizeRoute: HarmonizeRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  MappingRoute: MappingRoute,
  MigrationRoute: MigrationRoute,
  NationalCodesRoute: NationalCodesRoute,
  SettingsRoute: SettingsRoute,
  StandardizationRoute: StandardizationRoute,
  MaterialsIdRoute: MaterialsIdRoute,
  MaterialsIndexRoute: MaterialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
